//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string City { get; set; }
        public string NickName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> CareerId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    
        public virtual Career Career { get; set; }
        public virtual SystemRole SystemRole { get; set; }
    }
}
